# Generated by Django 5.0.4 on 2025-04-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_voucherphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='massage_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
